version: '3.8'

services:
  db:
    image: mysql
    container_name: expressdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express_ludycom
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/